# Generated by Django 4.2.5 on 2024-04-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_calif_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="calif", unique_together=set(),),
        migrations.AlterField(
            model_name="calif",
            name="alumno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.maestro",
                unique=True,
            ),
        ),
    ]
