# Generated by Django 4.2.5 on 2024-04-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_calif_unique_together_alter_calif_alumno"),
    ]

    operations = [
        migrations.RemoveField(model_name="calif", name="materia",),
    ]
