# Generated by Django 4.2.5 on 2024-04-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_calif_materia"),
    ]

    operations = [
        migrations.AddField(
            model_name="calif",
            name="materia",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.materia",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="calif",
            name="alumno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.alumno",
                unique=True,
            ),
        ),
    ]
