# Generated by Django 4.2.5 on 2024-04-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_calif_materia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calif",
            name="alumno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.alumno"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="calif", unique_together={("alumno", "materia")},
        ),
    ]
